<a href="https://colab.research.google.com/github/Bilol2747/python_darslarim/blob/main/Malumotlarga_ishlov_berish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import sqlite3 as sql
import numpy as np

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [ ]:
df.isnull().sum()

company              0
body-style           0
wheel-base          15
length              13
engine-type         12
num-of-cylinders     0
horsepower          16
average-mileage     15
price                3
dtype: int64

In [ ]:
len(df)

61

In [ ]:
df.isnull().sum()/len(df)*100

company              0.000000
body-style           0.000000
wheel-base          24.590164
length              21.311475
engine-type         19.672131
num-of-cylinders     0.000000
horsepower          26.229508
average-mileage     24.590164
price                4.918033
dtype: float64

In [ ]:
df.dropna()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0

In [ ]:
len(df.dropna())

14

In [ ]:
df.dropna(axis=1)

           company   body-style num-of-cylinders
index
0      alfa-romero  convertible             four
1      alfa-romero  convertible             four
2      alfa-romero    hatchback              six
3             audi        sedan             four
4             audi        sedan             five
...            ...          ...              ...
81      volkswagen        sedan             four
82      volkswagen        sedan             four
86      volkswagen        sedan             four
87           volvo        sedan             four
88           volvo        wagon             four

[61 rows x 3 columns]

In [ ]:
df.dropna(axis=1, thresh=45)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [ ]:
df2=df.dropna(subset=['price','horsepower'])
df2.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [ ]:
df.fillna(0)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,0.0,21.0,13495.0
1,alfa-romero,convertible,0.0,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,0.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,0.0,0.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,0.0,171.7,0,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,0.0,ohc,four,100.0,0.0,9995.0
87,volvo,sedan,104.3,188.8,0,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,0.0,23.0,13415.0

In [ ]:
df.fillna(99)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,99.0,21.0,13495.0
1,alfa-romero,convertible,99.0,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,99.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,99.0,99.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,99.0,171.7,99,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,99.0,ohc,four,100.0,99.0,9995.0
87,volvo,sedan,104.3,188.8,99,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,99.0,23.0,13415.0

In [ ]:
df.fillna({'horsepower':np.mean(df['horsepower']), 'wheel-base':np.mean(df['wheel-base'])})

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.600000,168.8,dohc,four,108.266667,21.0,13495.0
1,alfa-romero,convertible,99.219565,168.8,dohc,four,111.000000,21.0,16500.0
2,alfa-romero,hatchback,94.500000,171.2,ohcv,six,154.000000,NaN,16500.0
3,audi,sedan,99.800000,176.6,ohc,four,102.000000,24.0,13950.0
4,audi,sedan,99.400000,176.6,ohc,five,108.266667,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.300000,171.7,ohc,four,85.000000,27.0,7975.0
82,volkswagen,sedan,99.219565,171.7,NaN,four,52.000000,37.0,7995.0
86,volkswagen,sedan,97.300000,NaN,ohc,four,100.000000,NaN,9995.0
87,volvo,sedan,104.300000,188.8,NaN,four,114.000000,23.0,12940.0
88,volvo,wagon,104.300000,188.8,ohc,four,108.266667,23.0,13415.0

In [ ]:
np.mean(df['wheel-base'])

99.2195652173913

In [ ]:
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [ ]:
df.fillna(method='ffill')

<ipython-input-26-5c0beae7dc1e>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,21.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,102.0,24.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100.0,37.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114.0,23.0,13415.0

In [ ]:
df.fillna(method='bfill')

<ipython-input-27-b823574c06e2>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,13495.0
1,alfa-romero,convertible,94.5,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,24.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,110.0,19.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,188.8,ohc,four,100.0,23.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [ ]:
df[df.company=='toyota'].fillna(method='bfill')

<ipython-input-33-29c7b327e05f>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[df.company=='toyota'].fillna(method='bfill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,95.7,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6338.0
68,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,169.7,ohc,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,156.0,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0

In [ ]:
df[df.company=='toyota']=df[df.company=='toyota'].fillna(method='bfill')

<ipython-input-34-abd51be874e2>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[df.company=='toyota']=df[df.company=='toyota'].fillna(method='bfill')

In [ ]:
df[df.company=='toyota']

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,95.7,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6338.0
68,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,169.7,ohc,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,156.0,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0

In [ ]:
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [ ]:
df.fillna(df.mean())

TypeError: can only concatenate str (not "int") to str

In [ ]:
dfh= df[df['body-style']=='hatchback']

In [ ]:
 df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv')
df.head()

   rank  country     density   densityMi    pop2021   area
0     1    Macau  21946.4667  56841.3487    658.394     30
1     2   Monaco  19755.5000  51166.7450     39.511      2
2    28  Burundi    440.3044   1140.3884  12255.433  27834
3     1    Macau  21946.4667  56841.3487    658.394     30
4     2   Monaco  19755.5000  51166.7450     39.511      2

In [ ]:
df.duplicated()

0      False
1      False
2      False
3       True
4       True
       ...
242    False
243    False
244    False
245    False
246    False
Length: 247, dtype: bool

In [ ]:
df.shape

(247, 6)

In [ ]:
df.duplicated().sum()

15

In [ ]:
df.drop_duplicates()

     rank           country     density   densityMi    pop2021     area
0       1             Macau  21946.4667  56841.3487    658.394       30
1       2            Monaco  19755.5000  51166.7450     39.511        2
2      28           Burundi    440.3044   1140.3884  12255.433    27834
5       3         Singapore   8305.1915  21510.4461   5896.686      710
6       4         Hong Kong   6841.3134  17719.0017   7552.810     1104
..    ...               ...         ...         ...        ...      ...
242   228           Namibia      3.1338      8.1166   2587.344   825615
243   229    Western Sahara      2.3003      5.9577    611.875   266000
244   230          Mongolia      2.1286      5.5129   3329.289  1564110
245   231  Falkland Islands      0.2902      0.7517      3.533    12173
246   232         Greenland      0.0263      0.0680     56.877  2166086

[232 rows x 6 columns]

In [ ]:
df.drop_duplicates(['country'])

     rank           country     density   densityMi    pop2021     area
0       1             Macau  21946.4667  56841.3487    658.394       30
1       2            Monaco  19755.5000  51166.7450     39.511        2
2      28           Burundi    440.3044   1140.3884  12255.433    27834
5       3         Singapore   8305.1915  21510.4461   5896.686      710
6       4         Hong Kong   6841.3134  17719.0017   7552.810     1104
..    ...               ...         ...         ...        ...      ...
242   228           Namibia      3.1338      8.1166   2587.344   825615
243   229    Western Sahara      2.3003      5.9577    611.875   266000
244   230          Mongolia      2.1286      5.5129   3329.289  1564110
245   231  Falkland Islands      0.2902      0.7517      3.533    12173
246   232         Greenland      0.0263      0.0680     56.877  2166086

[232 rows x 6 columns]

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [ ]:
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [ ]:
dict={'two': 2, 'three':3, 'four':4, 'five':5, 'six':6, 'eight':8, 'twelve':12}
df['cylinder']=df['num-of-cylinders'].map(dict)
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinder
index,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5
...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4

In [ ]:
kurs=10720
df['price_uz']=df['price'].map(lambda x: x*kurs)
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinder,price_uz
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4,143808800.0

In [ ]:
df.replace('four', 4)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinder,price_uz
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,4,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,4,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,4,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,4,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,4,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,4,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,4,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,4,NaN,23.0,13415.0,4,143808800.0

In [ ]:
df2 = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv',index_col='country')
df2.head()

         rank     density   densityMi    pop2021   area
country
Macau       1  21946.4667  56841.3487    658.394     30
Monaco      2  19755.5000  51166.7450     39.511      2
Burundi    28    440.3044   1140.3884  12255.433  27834
Macau       1  21946.4667  56841.3487    658.394     30
Monaco      2  19755.5000  51166.7450     39.511      2

In [ ]:
df2.rename(index=str.upper)

                  rank     density   densityMi    pop2021     area
country
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
BURUNDI             28    440.3044   1140.3884  12255.433    27834
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
NAMIBIA            228      3.1338      8.1166   2587.344   825615
WESTERN SAHARA     229      2.3003      5.9577    611.875   266000
MONGOLIA           230      2.1286      5.5129   3329.289  1564110
FALKLAND ISLANDS   231      0.2902      0.7517      3.533    12173
GREENLAND          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [ ]:
df2.rename(columns=str.upper)

                  RANK     DENSITY   DENSITYMI    POP2021     AREA
country
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
Burundi             28    440.3044   1140.3884  12255.433    27834
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
Namibia            228      3.1338      8.1166   2587.344   825615
Western Sahara     229      2.3003      5.9577    611.875   266000
Mongolia           230      2.1286      5.5129   3329.289  1564110
Falkland Islands   231      0.2902      0.7517      3.533    12173
Greenland          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [ ]:
df2.rename(columns={"pop2021":"population"},index={"Macau":"Makau"}, inplace=True)

In [ ]:
df2

                  rank     density   densityMi  population     area
country
Makau                1  21946.4667  56841.3487     658.394       30
Monaco               2  19755.5000  51166.7450      39.511        2
Burundi             28    440.3044   1140.3884   12255.433    27834
Makau                1  21946.4667  56841.3487     658.394       30
Monaco               2  19755.5000  51166.7450      39.511        2
...                ...         ...         ...         ...      ...
Namibia            228      3.1338      8.1166    2587.344   825615
Western Sahara     229      2.3003      5.9577     611.875   266000
Mongolia           230      2.1286      5.5129    3329.289  1564110
Falkland Islands   231      0.2902      0.7517       3.533    12173
Greenland          232      0.0263      0.0680      56.877  2166086

[247 rows x 5 columns]

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv',usecols=['country','pop2021','area'] ,  index_col='country')
df.head()

           pop2021   area
country
Macau      658.394     30
Monaco      39.511      2
Burundi  12255.433  27834
Macau      658.394     30
Monaco      39.511      2

In [ ]:
df.loc['Uzbekistan']

pop2021     33935.763
area       447400.000
Name: Uzbekistan, dtype: float64

In [ ]:
bins = [0, 1000, 10000, 30000, 50000, 100000, 300000, 1500000]

In [ ]:
population= df.pop2021

In [ ]:
population

country
Macau                 658.394
Monaco                 39.511
Burundi             12255.433
Macau                 658.394
Monaco                 39.511
                      ...
Namibia              2587.344
Western Sahara        611.875
Mongolia             3329.289
Falkland Islands        3.533
Greenland              56.877
Name: pop2021, Length: 247, dtype: float64

In [ ]:
guruhlar=pd.cut(population,bins)
guruhlar

country
Macau                    (0, 1000]
Monaco                   (0, 1000]
Burundi             (10000, 30000]
Macau                    (0, 1000]
Monaco                   (0, 1000]
                         ...
Namibia              (1000, 10000]
Western Sahara           (0, 1000]
Mongolia             (1000, 10000]
Falkland Islands         (0, 1000]
Greenland                (0, 1000]
Name: pop2021, Length: 247, dtype: category
Categories (7, interval[int64, right]): [(0, 1000] < (1000, 10000] < (10000, 30000] <
                                         (30000, 50000] < (50000, 100000] < (100000, 300000] <
                                         (300000, 1500000]]

In [ ]:
guruhlar.value_counts()

pop2021
(0, 1000]            80
(1000, 10000]        73
(10000, 30000]       46
(30000, 50000]       19
(50000, 100000]      15
(100000, 300000]     11
(300000, 1500000]     3
Name: count, dtype: int64

In [ ]:
df['guruh']=guruhlar
df

                    pop2021     area           guruh
country
Macau               658.394       30       (0, 1000]
Monaco               39.511        2       (0, 1000]
Burundi           12255.433    27834  (10000, 30000]
Macau               658.394       30       (0, 1000]
Monaco               39.511        2       (0, 1000]
...                     ...      ...             ...
Namibia            2587.344   825615   (1000, 10000]
Western Sahara      611.875   266000       (0, 1000]
Mongolia           3329.289  1564110   (1000, 10000]
Falkland Islands      3.533    12173       (0, 1000]
Greenland            56.877  2166086       (0, 1000]

[247 rows x 3 columns]

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [ ]:
df.price.describe()

count       58.000000
mean     15387.000000
std      11320.259841
min       5151.000000
25%       6808.500000
50%      11095.000000
75%      18120.500000
max      45400.000000
Name: price, dtype: float64

In [ ]:
bins= [0, 10000, 20000, 50000]

In [ ]:
range= pd.cut(df.price, bins)
range

index
0     (10000, 20000]
1     (10000, 20000]
2     (10000, 20000]
3     (10000, 20000]
4     (10000, 20000]
           ...
81        (0, 10000]
82        (0, 10000]
86        (0, 10000]
87    (10000, 20000]
88    (10000, 20000]
Name: price, Length: 61, dtype: category
Categories (3, interval[int64, right]): [(0, 10000] < (10000, 20000] < (20000, 50000]]

In [ ]:
range.value_counts()

price
(0, 10000]        28
(10000, 20000]    17
(20000, 50000]    13
Name: count, dtype: int64

In [ ]:
names= ["arzon", "o'rta", "qimmat"]
range= pd.cut(df.price, bins, labels=names)

In [ ]:
range.value_counts()

price
arzon     28
o'rta     17
qimmat    13
Name: count, dtype: int64

In [ ]:
df['qiymat']=range
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,qiymat
index,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,o'rta
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,o'rta
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,o'rta
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,o'rta
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,o'rta
...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,arzon
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,arzon
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,arzon
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,o'rta
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,o'rta

In [ ]:
range=pd.cut(df.price,3)
range

index
0     (5110.751, 18567.333]
1     (5110.751, 18567.333]
2     (5110.751, 18567.333]
3     (5110.751, 18567.333]
4     (5110.751, 18567.333]
              ...
81    (5110.751, 18567.333]
82    (5110.751, 18567.333]
86    (5110.751, 18567.333]
87    (5110.751, 18567.333]
88    (5110.751, 18567.333]
Name: price, Length: 61, dtype: category
Categories (3, interval[float64, right]): [(5110.751, 18567.333] < (18567.333, 31983.667] <
                                           (31983.667, 45400.0]]

In [ ]:
range.value_counts()

price
(5110.751, 18567.333]     44
(31983.667, 45400.0]       9
(18567.333, 31983.667]     5
Name: count, dtype: int64

In [ ]:
range=pd.qcut(df.horsepower, 3)
range.value_counts()

horsepower
(51.999, 70.0]    18
(112.0, 262.0]    15
(70.0, 112.0]     12
Name: count, dtype: int64